services:
  - type: web
    name: api-trio-orcamento
    env: native
    plan: free
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FORNECEDOR_USER
      - key: FORNECEDOR_PASS